# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e722c29956db272a7b4d9c6921f04391d8cca52fc2194e34085b7003b0c15a3bc4da3f7d684016839864fd9aacbc37a93b3999b01baa05fc8b695d45088a1363

test:
  secret_key_base: 4cce3804fbdb34ddf9bd3f470fad686e912c63fea6fafecea49f140ec1638a6d202c9e919c8e3dfa0d9822d39d6155c0ed4bb05f37d7a4ebfba336f4b67c0c8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
